### ISSUE TITLE
Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 5

### ISSUE THREAD

**Issue by range-of-motion** [dunglas/frankenphp#582]
### What happened?

Not sure if this is due to FrankenPHP, but I don't have this issue using PHP-FPM. Whenever I try and send an e-mail using Laravel to Postmark, I get this. I already tried setting `MAIL_ENCRYPTION=null`, but no luck.

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### Relevant log output

```shell
[2024-02-17 21:29:14] production.ERROR: Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 5. OpenSSL Error messages:
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:0A000086:SSL routines::certificate verify failed {"userId":1,"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 5. OpenSSL Error messages:
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:0A000086:SSL routines::certificate verify failed at /var/www/spark-plug/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:171)
```
```

**Comment by withinboredom** [comment]
Are we missing ca-certificates @dunglas... that's a pretty weird error.

**Comment by dunglas** [comment]
This look like the same problem as https://github.com/beyondcode/expose/issues/391#issuecomment-1866184348 (Herd also uses static-php-cli under the hood as far as I know).

As the standalone binary doesn't bundle certificates, you need to point OpenSSL to your local certificates installation in your `php.ini` file (you can add one in the root of your app).

This is something that we need to document (help welcome).

**Comment by dunglas** [comment]
This likely doesn't work because it's impossible to reference the PEM file because the app is decompressed in a temporary directory with a random name.

Using a script to copy the PEM file in a known path (like /cacert.pem) could work as a workaround, but we need to figure out a better solution.

**Comment by hongfanmeng** [comment]
Hi, I also encountered the same problem

Are there any guides on how to resolve this issue?

**Comment by dunglas** [comment]
Here is what I think we should do:

1. Embed the latest version of the "official" cURL CA bundle when building the binary (allow the user to provide its own)
2. Extract the embedded bundle as a known path of it doesn't already exists
3. Change the default `php.ini` settings for cURL and OpenSSL to reference this bundle

**Comment by LukeAbell** [comment]
@dunglas Any chance there's a workaround in the meantime until this is resolved?

**Comment by dunglas** [comment]
Copying the CA bundle at a known path and hardcoding this absolute path in `php.ini` should work.

I'll try to take a look soon.

**Comment by SimonMacIntyre** [comment]
In case it helps anyone in the future, this caused me quite some headaches. In the end, I fixed it with these simple changes to my dockerfile:

```
RUN apk update && apk add --no-cache ca-certificates && rm -rf /var/cache/apk/*

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs
```

I was very confused why `laravel tinker` was working to send emails, but the web browser running frank was not. Then I noticed after dumping `openssl_get_cert_locations()` in both places that the results differed, which is where I saw frank was using the above environment variables.

**Comment by dunglas** [comment]
@SimonMacIntyre thanks! Would you mind opening a docs PR about that? I'm sure this will help a lot of people. In this file for instance: https://github.com/dunglas/frankenphp/blob/main/docs/known-issues.md

**Comment by SimonMacIntyre** [comment]
I'd be happy to!

**Comment by ichie-benjamin** [comment]
i have followed the documentation,
added
SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
SSL_CERT_DIR=/etc/ssl/certs

to .env,
reloaded nginx and octane but the issue persist,
I am using laravel forge

Connection could not be established with host "ssl://smtp-relay.brevo.com:465": stream_socket_client(): SSL operation failed with code 5. OpenSSL Error messages:
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:0A000086:SSL routines::certificate verify failed

**Comment by ReyKoxha** [comment]
Would be nice to have some movement with this bug. Unfortunately changing the environmental settings did not do the job for me with the standalone binary.

**Comment by withinboredom** [comment]
It's a known issue: https://github.com/dunglas/frankenphp/blob/main/docs/known-issues.md#troubleshooting-tlsssl-issues-with-static-binaries

**Comment by dunglas** [comment]
Closing as known issue with a known workaround (I plan to improve this in PHP directly at some point).
